### ISSUE TITLE
Weekly Report 2024-09-12

### ISSUE THREAD

**Issue by JingwenJessica** [Etown-CS/FairwayFinder#6]
What did you do this week?

**Comment by wetzelTanner** [comment]
I found more people for interviews and started creating a google form to ask interview questions to a wider group of people.

**Comment by pbgmidi** [comment]
I am looking into web scraping using JavaScript. This YouTube video goes over using playwright https://playwright.dev/ to scrap: https://www.youtube.com/watch?v=DOtJEwVsJic . Something I learned about scraping is that proxies can help mitigate websites from cutting off access when scraping. Also playwright is free and open source.

**Comment by SamH477** [comment]
This week, I sketched the search results page for our website and figured out UI features that will be important once we start building our site. Additionally, I started creating the templates for both user personas and stories in our wiki page.

**Comment by JingwenJessica** [comment]
@pbgmidi Let's create a folder for the web scraping feature we will implement. This will be a program running on the server side, and it won't have any direct interactions with our web app.
