### ISSUE TITLE
Weekly Report 9/19

### ISSUE THREAD

**Issue by wetzelTanner** [Etown-CS/FairwayFinder#9]
What did we do this week?

**Comment by wetzelTanner** [comment]
This week I helped to rough draft our website on paper and collected interview information from google forms to start creating our personas and user stories.

**Comment by pbgmidi** [comment]
I have made our mockup webpages in Justinmind and shared them with the team. I also did a bit of research on web crawling. https://pbgmidi.tech/cs401/FairwayHomepage

**Comment by SamH477** [comment]
This week, I finished the Client Interview and User Stories wiki pages. Additionally, I sketched UI designs for our website last class.
